/*
  # Create bulletins table

  1. New Tables
    - `bulletins`
      - `id` (bigint, primary key)
      - `title` (text)
      - `content` (text)
      - `created_at` (timestamp with time zone)

  2. Security
    - Enable RLS on `bulletins` table
    - Add policies for:
      - Public read access
      - Authenticated users can insert/update/delete
*/

CREATE TABLE IF NOT EXISTS bulletins (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  content text NOT NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE bulletins ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Bulletins are viewable by everyone"
  ON bulletins
  FOR SELECT
  TO public
  USING (true);

-- Allow authenticated users to insert
CREATE POLICY "Authenticated users can insert bulletins"
  ON bulletins
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Allow authenticated users to update their own bulletins
CREATE POLICY "Authenticated users can update bulletins"
  ON bulletins
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Allow authenticated users to delete bulletins
CREATE POLICY "Authenticated users can delete bulletins"
  ON bulletins
  FOR DELETE
  TO authenticated
  USING (true);